### ISSUE TITLE
如何生成方法复杂的options参数说明呢，options是个JSON对，有属性，有回调函数

### ISSUE THREAD

**Issue by xakoy** [zhh77/smartDoc#1]
比如: $.ajax这个方法，options选项有方法，有属性，还有字段，该怎么生成文档呢，开始以为用attrbute,event这种，后来才现搞错了

**Comment by zhh77** [comment]
很感谢你的反馈，目前可以使用另外构建一个options的class，然后设置类别为class，关联过去。后面版本我会用类似的方式来处理。

**Comment by xakoy** [comment]
OK , thanks.
